
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ./data/ipfs:/data/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    command: daemon --migrate --init
    restart: unless-stopped
    networks:
      default:
        aliases:
          - ipfs_node
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: decentralized_db
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-hive-db.sh:/docker-entrypoint-initdb.d/init-hive-db.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d hive_metastore"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  spark-worker:
    image: apache/spark:4.0.0-preview2
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
    # networks:
    #   - web3db-network
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://129.74.152.201:7077
  
  # node-app:
  #   build:
  #     context: ./node_app
  #   volumes:
  #     - ./node_app:/app
  #     - ./postgresql-42.6.0.jar:/app/postgresql-42.6.0.jar
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - ipfs
  #     - postgres
  #     - spark-master
  #     - hive-metastore
  #   environment:
  #     - FLASK_ENV=development
  #     - FLASK_DEBUG=1
  #     - POSTGRES_HOST=postgres
  #     - POSTGRES_DB=decentralized_db
  #     - POSTGRES_USER=dbuser
  #     - POSTGRES_PASSWORD=dbpassword
  #   command: flask run --host=0.0.0.0 --port=3000

  hive-metastore:
    image: apache/hive:3.1.3
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=postgres
      - DB_HOST=postgres
      - DB_NAME=hive_metastore
      - DB_USER=dbuser
      - DB_PASS=dbpassword
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionURL=jdbc:postgresql://postgres/hive_metastore
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionDriverName=org.postgresql.Driver
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionUserName=dbuser
      - HIVE_SITE_CONF_javax_jdo_option_ConnectionPassword=dbpassword
      - HIVE_SITE_CONF_datanucleus_autoCreateSchema=false
      - HIVE_SITE_CONF_hive_metastore_schema_verification=false
    ports:
      - "9083:9083"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./tmp:/tmp
    command: >
      sh -c "
        mkdir -p /tmp/hive &&
        chown -R hive:hive /tmp/hive &&
        /opt/hive/bin/schematool -dbType postgres -initSchema &&
        /opt/hive/bin/hive --service metastore
      "

volumes:
  postgres_data:
