version: '3.8'
services:
  ipfs:
    image: ipfs/go-ipfs:latest
    volumes:
      - ./data/ipfs:/data/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    command: daemon --migrate --init
    restart: unless-stopped
    networks:
      default:
        aliases:
          - ipfs_node

  spark-master:
    image: apache/spark:4.0.0-preview2
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_LOCAL_IP=spark-master
      - SPARK_CONF_DIR=/opt/spark/conf
    ports:
      - "7077:7077"
      - "8081:8080"
    volumes:
      - ./spark-app:/opt/spark/work-dir
    command: "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"

  spark-worker:
    image: apache/spark:4.0.0-preview2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
      - SPARK_DRIVER_MEMORY=1g
      - SPARK_EXECUTOR_MEMORY=1g
      - SPARK_WORKER_OPTS="-Dspark.worker.cleanup.enabled=true"
      - SPARK_LOG_LEVEL=DEBUG
      - SPARK_CONF_DIR=/opt/spark/conf
    volumes:
      - ./spark-app:/opt/spark/work-dir
    depends_on:
      - spark-master
    command: "/bin/bash -c '/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077 --webui-port 8081'"

  engine:
    build:
      context: ./engine
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - IPFS_HOST=ipfs
      - SPARK_MASTER=spark://spark-master:7077
    depends_on:
      - ipfs
      - spark-master
    networks:
      - spark-network
      - default
    volumes:
      - ./engine:/app

networks:
  spark-network:
    driver: bridge
  default:
    driver: bridge
