version: '3'
services:
  web3db-api:
    build:
      context: .
      dockerfile: Dockerfile
    image: web3db-api
    ports:
      - "80:80"
      - "443:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80;https://+:443
    restart: unless-stopped