services:
  # Spark Master Node
  spark-master:
    image: bitnami/spark:3.3.2
    container_name: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    ports:
      - "8080:8080"   # Spark master web UI
      - "7077:7077"   # Spark master service port
    networks:
      - app-net

  # Spark Worker Nodes
  spark-worker-1:
    build: ./spark-worker
    container_name: spark-worker-1
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    depends_on:
      - spark-master
    ports:
      - "8081:8081"   # Web UI for worker 1
    volumes:
      - shared_data:/data   # Single shared data volume
    networks:
      - app-net

  spark-worker-2:
    build: ./spark-worker
    container_name: spark-worker-2
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    depends_on:
      - spark-master
    ports:
      - "8082:8081"  
    volumes:
      - shared_data:/data   # Single shared data volume
    networks:
      - app-net

  spark-worker-3:
    build: ./spark-worker
    container_name: spark-worker-3
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1G
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
    depends_on:
      - spark-master
    ports:
      - "8083:8081"   # Web UI for worker 3 (mapped to host 8083)
    volumes:
      - shared_data:/data   # Single shared data volume
    networks:
      - app-net

  # Single IPFS Node
  ipfs:
    build: ./ipfs    # Build custom Dockerfile for IPFS
    container_name: ipfs
    networks:
      - app-net
    ports:
      - "5001:5001"   # IPFS API
      - "8091:8080"   # IPFS Gateway
      - "4001:4001"   # IPFS swarm port - add this for public network connectivity
    volumes:
      - ipfs_data:/data/ipfs   # Persist IPFS repository data

  # FastAPI Driver Server (Spark Driver)
  fastapi:
    build: ./fastapi
    container_name: fastapi-driver
    depends_on:
      - spark-master
      - spark-worker-1
      - spark-worker-2
      - spark-worker-3
      - ipfs
    networks:
      - app-net
    ports:
      - "8000:8000"   # FastAPI server port
    volumes:
      - shared_data:/data   # Single shared data volume

networks:
  app-net:
    driver: bridge

volumes:
  shared_data:   # Single shared data volume instead of partitioned chunks
  ipfs_data: