services:
  # Spark Master Node
  spark-master:
    image: bitnami/spark:3.3.2
    container_name: spark-master
    network_mode: host
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=${SPARK_MASTER_HOST}
      - SPARK_PUBLIC_DNS=${SPARK_PUBLIC_DNS}
      - SPARK_LOCAL_IP=${SPARK_LOCAL_IP}
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_MASTER_WEBUI_PORT=8080
