version: "3.8"

networks:
  web3dbnetwork:
    driver: overlay
    attachable: true

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/ipfsdata
    volumes:
      - ipfs_data:/ipfsdata
    ports:
      - "4001:4001"
      - "127.0.0.1:8080:8080"
      - "127.0.0.1:8083:8081"
      - "127.0.0.1:5003:5001"
    networks:
      - web3dbnetwork

  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    environment:
      - CLUSTER_NAME=test
      - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    ports:
      - 9870:9870
      - 9001:9000
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    networks:
      - web3dbnetwork

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
      CORE_CONF_fs_defaultFS: hdfs://namenode:9000
    env_file:
      - ./hadoop.env
    ports:
      - "9864:9864"
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    networks:
      - web3dbnetwork

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    ports:
      - "10000:10000"
    networks:
      - web3dbnetwork

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:9870 datanode:9864 hive-metastore-postgresql:5432"
    ports:
      - "9083:9083"
    networks:
      - web3dbnetwork

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    networks:
      - web3dbnetwork

  db_engine:
    build:
      context: ./db_engine
      dockerfile: Dockerfile
    image: web3db-engine
    ports:
      - "${DB_ENGINE_PORT:-3001}:3001"
      - "${P2P_PORT:-8000}:8000"
    environment:
      - IPFS_API_URL=http://ipfs:5001
      - SPARK_MASTER=spark://spark-master:7077
      - HIVE_METASTORE_URI=thrift://hive-metastore:9083
      - P2P_PORT=${P2P_PORT:-8000}
      - KNOWN_PEERS=${KNOWN_PEERS:-}
      - NODE_ID=${NODE_ID:-}
    depends_on:
      - ipfs
      - hive-server
      - hive-metastore
    networks:
      - web3dbnetwork
    deploy:
      mode: replicated
      replicas: ${NUM_NODES:-3}

volumes:
  hadoop_namenode:
  hadoop_datanode:
  hadoop_historyserver:
  ipfs_data: